test_that("aggreg_percent", {
    d <- data.frame(x = c(NA, F,F,T,F,T))
    expect_equal(aggreg_percent(d, "x", level = 1, use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = 2, use_na = TRUE), "50.00 %")
    expect_equal(aggreg_percent(d, "x", level = 3, use_na = TRUE), "16.67 %")
    expect_equal(aggreg_percent(d, "x", level = "TRUE", use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = "FALSE", use_na = TRUE), "50.00 %")
    expect_equal(aggreg_percent(d, "x", level = NA, use_na = TRUE), "16.67 %")

    d <- data.frame(x = factor(c("a", "b", "b", NA, NA, NA)))
    expect_equal(aggreg_percent(d, "x", level = 1, use_na = TRUE), "16.67 %")
    expect_equal(aggreg_percent(d, "x", level = 2, use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = 3, use_na = TRUE), "50.00 %")
    expect_equal(aggreg_percent(d, "x", level = "a", use_na = TRUE), "16.67 %")
    expect_equal(aggreg_percent(d, "x", level = "b", use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = NA, use_na = TRUE), "50.00 %")

    d <- data.frame(x = factor(c(3, 2, 1, 2, 2, 1)))
    expect_equal(aggreg_percent(d, "x", level = 1, use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = 2, use_na = TRUE), "50.00 %")
    expect_equal(aggreg_percent(d, "x", level = 3, use_na = TRUE), "16.67 %")
    expect_equal(aggreg_percent(d, "x", level = "1", use_na = TRUE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = "2", use_na = TRUE), "50.00 %")
    expect_equal(aggreg_percent(d, "x", level = "3", use_na = TRUE), "16.67 %")


    d <- data.frame(x = c(NA, F,F,T,F,T))
    expect_equal(aggreg_percent(d, "x", level = 1, use_na = FALSE), "40.00 %")
    expect_equal(aggreg_percent(d, "x", level = 2, use_na = FALSE), "60.00 %")
    expect_equal(aggreg_percent(d, "x", level = 3, use_na = FALSE), "0.00 %")
    expect_equal(aggreg_percent(d, "x", level = "TRUE", use_na = FALSE), "40.00 %")
    expect_equal(aggreg_percent(d, "x", level = "FALSE", use_na = FALSE), "60.00 %")
    expect_equal(aggreg_percent(d, "x", level = NA, use_na = FALSE), "0.00 %")

    d <- data.frame(x = factor(c("a", "b", "b", NA, NA, NA)))
    expect_equal(aggreg_percent(d, "x", level = 1, use_na = FALSE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = 2, use_na = FALSE), "66.67 %")
    expect_equal(aggreg_percent(d, "x", level = 3, use_na = FALSE), "0.00 %")
    expect_equal(aggreg_percent(d, "x", level = "a", use_na = FALSE), "33.33 %")
    expect_equal(aggreg_percent(d, "x", level = "b", use_na = FALSE), "66.67 %")
    expect_equal(aggreg_percent(d, "x", level = NA, use_na = FALSE), "0.00 %")
})
