test_that("aggreg_percent", {
    x <- c(NA, F,F,T,F,T)
    expect_equal(aggreg_percent(x, level = 1, use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = 2, use_na = TRUE), 3/6)
    expect_equal(aggreg_percent(x, level = 3, use_na = TRUE), 1/6)
    expect_equal(aggreg_percent(x, level = "TRUE", use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = "FALSE", use_na = TRUE), 3/6)
    expect_equal(aggreg_percent(x, level = NA, use_na = TRUE), 1/6)

    x <- factor(c("a", "b", "b", NA, NA, NA))
    expect_equal(aggreg_percent(x, level = 1, use_na = TRUE), 1/6)
    expect_equal(aggreg_percent(x, level = 2, use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = 3, use_na = TRUE), 3/6)
    expect_equal(aggreg_percent(x, level = "a", use_na = TRUE), 1/6)
    expect_equal(aggreg_percent(x, level = "b", use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = NA, use_na = TRUE), 3/6)

    x <- factor(c(3, 2, 1, 2, 2, 1))
    expect_equal(aggreg_percent(x, level = 1, use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = 2, use_na = TRUE), 3/6)
    expect_equal(aggreg_percent(x, level = 3, use_na = TRUE), 1/6)
    expect_equal(aggreg_percent(x, level = "1", use_na = TRUE), 2/6)
    expect_equal(aggreg_percent(x, level = "2", use_na = TRUE), 3/6)
    expect_equal(aggreg_percent(x, level = "3", use_na = TRUE), 1/6)


    x <- c(NA, F,F,T,F,T)
    expect_equal(aggreg_percent(x, level = 1, use_na = FALSE), 2/5)
    expect_equal(aggreg_percent(x, level = 2, use_na = FALSE), 3/5)
    expect_equal(aggreg_percent(x, level = 3, use_na = FALSE), 0/5)
    expect_equal(aggreg_percent(x, level = "TRUE", use_na = FALSE), 2/5)
    expect_equal(aggreg_percent(x, level = "FALSE", use_na = FALSE), 3/5)
    expect_equal(aggreg_percent(x, level = NA, use_na = FALSE), 0/5)

    x <- factor(c("a", "b", "b", NA, NA, NA))
    expect_equal(aggreg_percent(x, level = 1, use_na = FALSE), 1/3)
    expect_equal(aggreg_percent(x, level = 2, use_na = FALSE), 2/3)
    expect_equal(aggreg_percent(x, level = 3, use_na = FALSE), 0/3)
    expect_equal(aggreg_percent(x, level = "a", use_na = FALSE), 1/3)
    expect_equal(aggreg_percent(x, level = "b", use_na = FALSE), 2/3)
    expect_equal(aggreg_percent(x, level = NA, use_na = FALSE), 0/3)
})
