test_that("aggreg_count", {
    x <- c(NA, F,F,T,F,T)
    expect_equal(aggreg_count(x, level = 1), 2)
    expect_equal(aggreg_count(x, level = 2), 3)
    expect_equal(aggreg_count(x, level = 3), 1)
    expect_equal(aggreg_count(x, level = "TRUE"), 2)
    expect_equal(aggreg_count(x, level = "FALSE"), 3)
    expect_equal(aggreg_count(x, level = NA), 1)

    x <- factor(c("a", "b", "b", NA, NA, NA))
    expect_equal(aggreg_count(x, level = 1), 1)
    expect_equal(aggreg_count(x, level = 2), 2)
    expect_equal(aggreg_count(x, level = 3), 3)
    expect_equal(aggreg_count(x, level = "a"), 1)
    expect_equal(aggreg_count(x, level = "b"), 2)
    expect_equal(aggreg_count(x, level = NA), 3)

    x <- factor(c(3, 2, 1, 2, 2, 1))
    expect_equal(aggreg_count(x, level = 1), 2)
    expect_equal(aggreg_count(x, level = 2), 3)
    expect_equal(aggreg_count(x, level = 3), 1)
    expect_equal(aggreg_count(x, level = "1"), 2)
    expect_equal(aggreg_count(x, level = "2"), 3)
    expect_equal(aggreg_count(x, level = "3"), 1)
})
