#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom dplyr as_tibble
#' @importFrom dplyr bind_rows
#' @importFrom dplyr group_by
#' @importFrom dplyr group_indices
#' @importFrom dplyr group_keys
#' @importFrom dplyr group_rows
#' @importFrom dplyr n_groups
#' @importFrom dplyr tibble
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 geom_abline
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_density
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_errorbarh
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_linerange
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_rug
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 stat_qq
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 ylim
#' @importFrom graphics boxplot
#' @importFrom grDevices nclass.Sturges
#' @importFrom rlang .data
#' @importFrom rlang caller_env
#' @importFrom rlang is_integer
#' @importFrom rlang is_integerish
#' @importFrom rlang is_scalar_atomic
#' @importFrom rlang is_scalar_character
#' @importFrom rlang is_scalar_double
#' @importFrom rlang is_scalar_integerish
#' @importFrom rlang is_scalar_logical
#' @importFrom stats aov
#' @importFrom stats as.formula
#' @importFrom stats chisq.test
#' @importFrom stats fisher.test
#' @importFrom stats kruskal.test
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats p.adjust
#' @importFrom stats p.adjust.methods
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats shapiro.test
#' @importFrom stats t.test
#' @importFrom stats wilcox.test
#' @importFrom vctrs list_of
## usethis namespace: end
NULL
